kind: pipeline
type: docker
name: test

steps:
- name: backend
  image: golang
  commands:
  - go build
  - go test

- name: frontend
  image: node
  commands:
  - npm install
  

  depends_on:
  - frontend
  - backend
